import type { Metadata } from "next";
import "@/app/globals.css";


export const metadata: Metadata = {
  title: "LinkScribe",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale: string};
}) {
  return (
    <html lang={locale}>
      <body>{children}</body>
    </html>
  );
}
