# Utiliza la imagen oficial de PostgreSQL desde Docker Hub
FROM postgres

# Copia el contenido de tu carpeta local 'data' al directorio de datos de PostgreSQL en el contenedor
COPY data-postgres /var/lib/postgresql/data/
